version: 2
jobs:
  docker:
    - image: circleci/buildpack-deps:trusty
  build:
    environment:
      NODE_VERSION: 8.14.0
      METEOR_PRETTY_OUTPUT: 0
      METEOR_WAREHOUSE_URLBASE: https://d3fm2vapipm3k9.cloudfront.net
    steps:
    - checkout
    - setup_remote_docker
    - run: nvm install $NODE_VERSION && nvm alias default $NODE_VERSION
    - run: test -f $HOME/.meteor/meteor || (curl https://install.meteor.com | sh)
    - run: sudo ln -s $HOME/.meteor/meteor /usr/bin/meteor
    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.meteor
    - run: ./admin/run_tests.sh

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
