version: 2
jobs:
  build:
    parallelism: 4
    docker:
      - image: circleci/node:8.16.1
    environment:
      NODE_VERSION: 8.16.1
      METEOR_PRETTY_OUTPUT: 0
      METEOR_WAREHOUSE_URLBASE: https://d3fm2vapipm3k9.cloudfront.net
    steps:
    - checkout
    - setup_remote_docker
    - run: test -f $HOME/.meteor/meteor || (curl https://install.meteor.com | sh)
    - run: pwd
    - run: echo $PATH
    - run: test -e /usr/local/bin/meteor || ln -s $HOME/.meteor/meteor /usr/local/bin/meteor
    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.meteor
    - run: docker images
    - run: ./admin/run_tests.sh

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
